name: NPM Audit

on:
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '0 4 * * *'

permissions:
  contents: read

jobs:
  audit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Use Node.js 18
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run npm audit
        run: npm audit --audit-level=high --json > audit.json || true

      - name: Fail on high/critical vulnerabilities
        run: |
          node -e "const fs=require('fs');const r=JSON.parse(fs.readFileSync('audit.json','utf8'));const advisories=(r.vulnerabilities)||{};const sev=['critical','high'];let fail=false;for(const [name,info] of Object.entries(advisories)){if(sev.includes(info.severity)){fail=true}};if(fail){console.error('High/Critical vulnerabilities found');process.exit(1)} else {console.log('No high/critical vulnerabilities')}}"
