name: NPM Audit

on:
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '0 4 * * *'

permissions:
  contents: read

jobs:
  audit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Use Node.js 18
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run npm audit
        run: npm audit --audit-level=high --json > audit.json || true

      - name: Fail on high/critical vulnerabilities
        run: |
          node -e "const fs=require('fs');let r;try{r=JSON.parse(fs.readFileSync('audit.json','utf8'))}catch(e){console.error('audit.json not found or invalid');process.exit(1)};const src=r.vulnerabilities||r.advisories||{};const list=Array.isArray(src)?src:Object.values(src);const fail=list.some(v=>['high','critical'].includes((v&&v.severity)||''));if(fail){console.error('High/Critical vulnerabilities found');process.exit(1)}else{console.log('No high/critical vulnerabilities')}"
