name: Secret Scanning (Trivy)

on:
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '0 2 * * *'

permissions:
  contents: read

jobs:
  trivy-secret-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Run Trivy secret scan
        uses: aquasecurity/trivy-action@0.33.1
        with:
          scan-type: fs
          scanners: secret
          format: table
          ignore-unfixed: true
          exit-code: '1'
          severity: HIGH,CRITICAL
